### PR TITLE
Use passwd + other fixes

### PR DESCRIPTION
**Pull request by xdissent**

### CODE REVIEW

**Comment by pkrumins** [comment]
Why does it say `module.exports = new function () {` than just `module.exports = function () {`?

Why is there a `new`?

**Comment by pkrumins** [comment]
Otherwise cool patch.

**Comment by xdissent** [comment]
Oh, I was calling new because all the docs indicated the module exported an object rather than a function. Also could just return `this` in the function and call the function immediately if that's preferable.

**Comment by pkrumins** [comment]
Oh I see! I npm published this as 0.0.2!

**Pull request merged**
